GM.Shop = {
	["Weapons"] = {
		{ "Pistol", "weapon_pistol", 10 },
		{ "SMG", "weapon_smg1", 25 },
		{ "Shotgun", "weapon_shotgun", 40 },
		{ ".357", "weapon_357", 40 },
		{ "Medkit", "weapon_medkit", 75 },
		{ "Crossbow", "weapon_crossbow", 75 },
		{ "Gravgun", "weapon_physcannon", 30 },
		{ "MP5", "weapon_raid_smg" , 20},
		{ "AR2", "weapon_ar2", 100 },
		{ "RPG", "weapon_rpg", 100 },
		{ "Grenade", "weapon_frag", 10, true },
		{ "Bugbait", "weapon_bugbait", 10, true },
	},
	["Ammo"] = {
		{ "Pistol", "item_ammo_pistol", 5 },
		{ "Pistol x5", "item_ammo_pistol_large", 25 },
		{ "SMG", "item_ammo_smg1", 10 },
		{ "Shotgun", "item_box_buckshot", 30 },
		{ ".357", "item_ammo_357", 10 },
		{ "Crossbow", "item_ammo_crossbow", 30 },
		{ "AR2", "item_ammo_ar2", 15 },
		{ "AR2 Alt", "item_ammo_ar2_altfire", 20 },
		{ "SMG Alt", "item_ammo_smg1_grenade", 20 },
		{ "RPG", "item_rpg_round", 20 },
	},
	["Other"] = {
		{ "Armour", "item_battery", 20 },
		{ "Health", "item_healthkit", 15 },
		{ "Minor Health", "item_healthvial", 5 },
		{ "Dynamic", "item_dynamic_resupply", 50 },
	},
};

GM.Weapons = { -- second value is the danger level increase for each weapon
	{ "weapon_crowbar", 0.5 }, -- base player threat
	{ "weapon_pistol", 0.25 },
	{ "weapon_smg1", 0.25 },
	{ "weapon_shotgun", 0.25 },
	{ "weapon_357", 0.25 },
	{ "weapon_medkit", 0.25 },
	{ "weapon_crossbow", 0.25 },
	{ "weapon_raid_smg" , 0.1},
	{ "weapon_ar2", 0.25 },
	{ "weapon_rpg", 0.25 },
	{ "weapon_frag", 0.25 },
	{ "weapon_bugbait", 0 }, -- maybe bugbait should be an investment to lower threat
	{ "weapon_bfg_beta_spas", 0.25 }, -- I briefly experimented with a workshop addon's weapons but was not happy with their balence.
	{ "weapon_bfg_mp7", 0.35 },
	{ "weapon_bfg_smg2", 0.35 },
	{ "weapon_bfg_assasin_pistols", 0.35 },
	{ "weapon_bfg_ar1", 0.5 },
	{ "weapon_bfg_hmg", 1 },
	{ "weapon_bfg_oicw", 0.75 },
	{ "weapon_bfg_hl2_sniper", 0.75 },
	{ "weapon_bfg_hl2_annabelle", 0.35 },
	{ "weapon_stunstick", 0.5},
};

GM.RebelModels = {
	"models/Humans/Group03/male_01.mdl",
	"models/Humans/Group03/male_02.mdl",
	"models/Humans/Group03/male_03.mdl",
	"models/Humans/Group03/male_04.mdl",
	"models/Humans/Group03/male_05.mdl",
	"models/Humans/Group03/male_06.mdl",
	"models/Humans/Group03/male_07.mdl",
	"models/Humans/Group03/male_08.mdl",
	"models/Humans/Group03/male_09.mdl",
	"models/Humans/Group03/female_01.mdl",
	"models/Humans/Group03/female_02.mdl",
	"models/Humans/Group03/female_03.mdl",
	"models/Humans/Group03/female_04.mdl",
	"models/Humans/Group03/female_05.mdl",
	"models/Humans/Group03/female_06.mdl",
--[["models/Humans/Group03m/male_01.mdl",
	"models/Humans/Group03m/male_02.mdl",
	"models/Humans/Group03m/male_03.mdl",
	"models/Humans/Group03m/male_04.mdl",
	"models/Humans/Group03m/male_05.mdl",
	"models/Humans/Group03m/male_06.mdl",
	"models/Humans/Group03m/male_07.mdl",
	"models/Humans/Group03m/male_08.mdl",
	"models/Humans/Group03m/male_09.mdl",
	"models/Humans/Group03m/female_01.mdl",
	"models/Humans/Group03m/female_02.mdl",
	"models/Humans/Group03m/female_03.mdl",
	"models/Humans/Group03m/female_04.mdl",
	"models/Humans/Group03m/female_05.mdl",
	"models/Humans/Group03m/female_06.mdl"--]]
};